export const VEHICLES = [
  {
    name: 'Suzuki WagonR',
    image: '/assets/vehicles/1.jpg',
    category: 'Budget',
    label: 'Suzuki WagonR',
    price: '3000',
    pricewithDriver: '3500',
    capacity: 4,
    featured: true,
  },
  {
    name: 'Toyota Vitz',
    image: '/assets/vehicles/2.jpg',
    category: 'Budget',
    label: 'Toyota Vitz',
    price: '3200',
    pricewithDriver: '4000',
    capacity: 4,
    featured: true,
  },
  {
    name: 'Suzuki Swift',
    image: '/assets/vehicles/3.jpg',
    category: 'Budget',
    label: 'Suzuki Swift',
    price: '3200',
    pricewithDriver: '4000',
    capacity: 4,
    featured: true,
  },
  {
    name: '	Suzuki Cultus',
    image: '/assets/vehicles/4.jpg',
    category: 'Budget',
    label: ' Suzuki Cultus',
    price: '3500',
    pricewithDriver: '4000',

    capacity: 4,
    featured: true,
  },
  {
    name: 'Toyota XLI',
    image: '/assets/vehicles/2-1.jpg',
    category: 'Executive',
    label: 'Toyota XLI',
    price: '4200',
    pricewithDriver: '5000',
    capacity: 4,
    featured: true,
  },
  {
    name: 'Toyota GLI (Automatic)',
    image: '/assets/vehicles/2-2.jpg',
    category: 'Executive',
    label: 'Toyota GLI (Automatic)',
    price: '4500',
    pricewithDriver: '5500',
    capacity: 4,
    featured: true,
  },
  {
    name: 'Honda City',
    image: '/assets/vehicles/2-3.jpg',
    category: 'Executive',
    label: 'Honda City',
    price: '4100',
    pricewithDriver: '5500',
    capacity: 4,
    featured: true,
  },
  {
    name: 'Honda Civic (Automatic)',
    image: '/assets/vehicles/2-4.jpg',
    category: 'Executive',
    label: 'Honda Civic (Automatic)',
    price: '5200',
    pricewithDriver: '6000',
    capacity: 4,
    featured: true,
  },

  {
    name: 'Mercedez Benz',
    image: '/assets/vehicles/3-1.jpg',
    category: 'Luxury',
    label: 'Mercedez Benz',
    price: '15000',
    pricewithDriver: '17000',
    capacity: 4,
    featured: true,
  },
  {
    name: 'BMW',
    image: '/assets/vehicles/3-2.jpg',
    category: 'Luxury',
    label: 'BMW',
    price: '25000',
    pricewithDriver: '27000',
    capacity: 4,
    featured: true,
  },
  {
    name: 'Audi',
    image: '/assets/vehicles/3-3.jpg',
    category: 'Luxury',
    label: 'Audi',
    price: '32000',
    pricewithDriver: '35000',
    capacity: 4,
    featured: true,
  },
  {
    name: 'Toyota Land Cruiser',
    image: '/assets/vehicles/3-4.jpg',
    category: 'Luxury',
    label: 'Toyota Land Cruiser',
    price: '31000',
    pricewithDriver: '34000',
    capacity: 4,
    featured: true,
  },
  {
    name: 'Toyota Coaster',
    image: '/assets/vehicles/4-1.jpg',
    category: 'Busses & Vans',
    label: 'Toyota Coaster',
    price: '8000',
    pricewithDriver: '9000',
    capacity: 19,
    featured: true,
  },
  {
    name: 'Toyota Coaster (Ceylon)',
    image: '/assets/vehicles/4-1.jpg',
    category: 'Busses & Vans',
    label: 'Toyota Coaster (Ceylon)',
    price: '9500',
    pricewithDriver: '11000',
    capacity: 23,
    featured: true,
  },
  {
    name: '	Toyota Hiace',
    image: '/assets/vehicles/4-4.jpg',
    category: 'Busses & Vans',
    label: 'Toyota Hiace',
    price: '7600',
    pricewithDriver: '9000',
    capacity: 14,
    featured: true,
  },
];
